firstname = input("Given name: ")
lastname = input("Family name: ")
print(firstname + " " + lastname)
streetaddress = input("Street address: ")
address = input("City and postal code: ")
print(streetaddress)
print(address)